default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5)%>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>

development:
  <<: *default
  database: todo_ror_vue_development

test:
  <<: *default
  database: todo_ror_vue_test

production:
  <<: *default
  database: todo_ror_vue_production
  username: <%= ENV['TODO_ROR_VUE_DATABASE_USER'] %>
  password: <%= ENV['TODO_ROR_VUE_DATABASE_PASSWORD'] %>
