default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: todo_ror_vue_development

test:
  <<: *default
  database: todo_ror_vue_test

production:
  <<: *default
  database: todo_ror_vue_production
  username: <%= ENV["TODO_ROR_VUE_DATABASE_USERNAME"] %>
  password: <%= ENV["TODO_ROR_VUE_DATABASE_PASSWORD"] %>
