<template>
  <form @submit.prevent="enableOTPAuth(otpAuth.links.otp_auth_path, otpAuth.enableParams)">
    <OtpAuthStatusBadge
      :value="otpAuth.otp_required_for_login"
      class="mb-4"
    />

    <OtpBackupCodesGrid
      v-if="otpAuth.otp_required_for_login"
      :otp-backup-codes="otpAuth.otp_backup_codes"
    />

    <div
      v-else
      class="grid grid-cols-2 gap-2"
    >
      <div class="col-span-2">
        <h4 class="text-md font-medium mb-3">
          Step 1: Scan QR Code
        </h4>

        <p>
          Please scan the QR code below using an OTP compatible app such as Google Authenticator or Auth. <br>
          If you cannot use QR code, enter the following code manually:
          <code class="text-sm bg-gray-200 p-1">{{ otpAuth.otp_secret_key }}</code>
        </p>

        <div class="flex justify-center py-6">
          <ToggleButton
            v-if="!qrcodeVisibile"
            v-model="qrcodeVisibile"
            off-label="Show QR Code"
          />

          <!-- eslint-disable vue/no-v-html -->
          <div
            v-if="qrcodeVisibile"
            v-html="otpAuth.qrcode_svg"
          />
        </div>
      </div>

      <div class="col-span-2">
        <div class="pb-6">
          <h4 class="text-md font-medium mb-3">
            Step 2: Confirm OTP Code
          </h4>

          <p>Please confirm the code generated by OTP compatible app to enable two factor authentication</p>
        </div>
      </div>

      <div class="col-span-2">
        <InputField
          :errors="errors.current_password"
          label-for="otp_auth_current_password"
          label="Current Password"
          class="mb-3"
        >
          <InputText
            v-model="otpAuth.current_password"
            :invalid="!!errors.current_password"
            name="otp_auth[current_password]"
            id="otp_auth_current_password"
            class="w-full"
            type="password"
          />
        </InputField>
      </div>

      <div class="col-span-2">
        <InputField
          :errors="errors.otp_code"
          label-for="otp_auth_otp_code"
          label="OTP Code"
          class="mb-3"
        >
          <InputText
            v-model="otpAuth.otp_code"
            :invalid="!!errors.otp_code"
            name="otp_auth[otp_code]"
            id="otp_auth_otp_code"
            class="w-full"
            type="text"
          />
        </InputField>
      </div>

      <div class="col-span-2">
        <button
          class="btn btn--primary w-full"
          type="submit"
        >
          Enable 2FA
        </button>
      </div>
    </div>
  </form>
</template>

<script lang="ts" setup>
//- Libs
import { PropType, ref } from 'vue'
//- Models
import { OTPAuthModel } from '@components/user_panel/otp_auth/models/otpAuth'
//- Composables
import useOTPAuth from '@components/user_panel/otp_auth/composables/useOTPAuth'
//- Components
import OtpAuthStatusBadge from '@components/user_panel/otp_auth/OtpAuthStatusBadge.vue'
import OtpBackupCodesGrid from '@components/user_panel/otp_auth/OtpBackupCodesGrid.vue'
import InputField from '@components/shared/fields/InputField.vue'
import InputText from 'primevue/inputtext'
import ToggleButton from 'primevue/togglebutton'

const props = defineProps({
  otp_auth: {
    type: Object as PropType<OTPAuthModel>,
    required: true
  }
})

const qrcodeVisibile = ref<boolean>(false)
const { otpAuth, errors, enableOTPAuth } = useOTPAuth(props.otp_auth)
</script>
