<template>
  <form @submit.prevent="handleSubmit">
    <p class="text-md mb-8">
      Please enter a code generated by OTP compatible app such as Google Authenticator or Authy:
    </p>

    <InputField
      :errors="errors.otp_code"
      label-for="otp_auth_otp_code"
      label="Code"
      class="mb-3"
    >
      <InputText
        v-model="otpAuth.otp_code"
        :invalid="!!errors.otp_code"
        name="otp_auth[otp_code]"
        id="otp_auth_otp_code"
        class="w-full"
        type="text"
      />
    </InputField>

    <div class="my-8">
      <button
        type="submit"
        class="btn btn--primary w-full"
      >
        Continue
      </button>
    </div>
  </form>

  <div class="my-8">
    <button
      @click="signOut"
      class="btn w-full"
    >
      <i class="icon icon-logout" />
      Log Out
    </button>
  </div>
</template>

<script lang="ts" setup>
//- Libs
import { PropType } from 'vue'
//- Models
import type { TVerifyFormLinks } from '@components/user_panel/otp_auth/types'
//- Composables
import useOTPAuth from '@components/user_panel/otp_auth/composables/useOTPAuth'
//- Components
import InputField from '@components/shared/fields/InputField.vue'
import InputText from 'primevue/inputtext'
//- Utils
import useHTTP from '@utils/useHTTP'

const props = defineProps({
  links: {
    type: Object as PropType<TVerifyFormLinks>,
    required: true
  }
})

const { otpAuth, errors, verifyOTPCode } = useOTPAuth()

const handleSubmit = () => {
  verifyOTPCode(props.links.submit_path, otpAuth.value.verifyParams)
    .then(() => window.location.pathname = props.links.redirect_path)
}

const signOut = () => {
  useHTTP(props.links.sign_out_path, { method: 'DELETE' })
    .then(() => window.location.pathname = '/')
}
</script>
